add glob2csv.sh, fiddle with pre-commit hooks, link to vim-puppet, etc
* vim bash keybindings
* vim split screen keybindings

diff --git a/git/git_template/hooks/pre-commit b/git/git_template/hooks/pre-commit
--- a/git/git_template/hooks/pre-commit
+++ b/git/git_template/hooks/pre-commit
@@ -3,9 +3,15 @@
 # Called by "git commit" with no arguments.
 # The hook should exit with non-zero status after issuing an
 # appropriate message if it wants to stop the commit.
+#
+# TODO: check more pry/debug statements
+# TODO: check ruby syntax (ruby -c ?)
+# TODO: ruby linter
+# TODO: more strict checking: no spaces after parens (linter?). spaces after commas, 80 chars
+
 
 # ensure this isn't run against non-staged files
-git stash -q --keep-index
+git stash --quiet --keep-index --include-untracked
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -16,6 +22,7 @@ else
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
+#   or: place a file that returns non-zero in hooks/allownonascii
 allownonascii=$(git config --bool hooks.allownonascii)
 
 # Redirect output to stderr.
@@ -42,16 +49,12 @@ EOF
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
-# TODO: doesn't print the offending filenames
-exec git diff-index --check --cached $against --
-  RESULT=$?
-# TODO: write an exit function that pops from stash
-#[ $RESULT -ne 0 ] && exit 1
+#   defaults to trailing whitespace and whitespace followed by tab at indent
+git diff-index --check --cached $against --
+RESULT=$?
+if [ $RESULT -ne 0 ]; then
+  git stash pop -q
+  exit 1
+fi
 
-# check for binding.pry
-exec .git/hooks/pre-commit-pry
-  RESULT=$?
-# pop the stash from top
-exec git stash pop -q
-[ $RESULT -ne 0 ] && exit 1
 exit 0
